names = ['Abe', 'Jelyn', 'Tonton', '', 'Cris']
for name in names:
    if name == '':
        print('Empty value Detected!')
        continue
    print(f'Name = {name}')
    

grocery = [
    '',
    'Bigas',
    'Asukal',
    '',
    'Asin',
    'Mantika',
    'Toyo',
    '',
    'Suka',
    'Patis',
    'Paminta',
    'Bawang',
    '',
    'Sibuyas',
    'Kamatis',
    'Luya',
    'Siling Labuyo',
    '',
    'Siling Haba',
    'Itlog',
    'Hotdog',
    '',
    'Longganisa',
    'Tocino',
    'Bacon',
    '',
    'Ham',
    'Corned Beef',
    'Sardinas',
    '',
    'Tuna',
    'Century Tuna',
    'Spam',
    '',
    'Meat Loaf',
    'Gatas',
    'Powdered Milk',
    '',
    'Condensed Milk',
    'Evaporated Milk',
    'Kape',
    '3-in-1 Coffee',
    '',
    'Tsaa',
    'Milo',
    'Cereal',
    'Tinapay',
    '',
    'Pandesal',
    'Gardenia',
    'Peanut Butter',
    'Jam',
    '',
    'Mayonnaise',
    'Ketchup',
    'Mustasa',
    '',
    'Spaghetti Sauce',
    'Tomato Sauce',
    'Pasta',
    'Macaroni',
    '',
    'Instant Noodles',
    'Cup Noodles',
    'Oatmeal',
    '',
    'Biskwit',
    'Crackers',
    'Chips',
    'Chichirya',
    '',
    'Chocolate',
    'Candy',
    'Ice Cream',
    '',
    'Yogurt',
    'Cheese',
    'Butter',
    'Margarine',
    '',
    'Chicken',
    'Pork',
    'Beef',
    '',
    'Isda',
    'Tilapia',
    'Bangus',
    'Hipon',
    'Alamang',
    '',
    'Talong',
    'Kalabasa',
    'Sayote',
    'Repolyo',
    '',
    'Carrots',
    'Patatas',
    'Pechay',
    'Kangkong',
    '',
    'Pipino',
    'Lettuce',
    'Apple',
    'Orange',
    '',
    'Saging',
    'Mango',
    'Grapes',
    'Pineapple',
    '',
    'Watermelon',
    'Dishwashing Liquid',
    'Laundry Detergent',
    '',
    'Fabric Conditioner',
    'Bath Soap',
    'Shampoo',
    'Conditioner',
    '',
    'Toothpaste',
    'Toothbrush',
    'Alcohol',
    'Tissue',
    '',
    'Paper Towel',
    'Trash Bag',
    'Sponge',
    '', 
    'Floor Cleaner',
    'Air Freshener',
    '']
for grocer in grocery:
    if grocer == '':
       print('Item:Out of Stock')
       continue
    print(f'Item:{grocer}')